### ISSUE TITLE
how to run feedsearch crawler on a list

### ISSUE THREAD

**Issue by infominer33** [DBeath/feedsearch-crawler#3]
I borrowed some of the command from the other issue, but I'm unfamiliar with Python syntax\shell.

Trying to crawl a list of urls:

```
from feedsearch_crawler import search(Union[str, List[str]])
import logging
logging.basicConfig(filename='example.log',level=logging.DEBUG)
feeds = search('https://aaronparecki.com/articles, https://altmode.org')
print(feeds)
logger = logging.getLogger("feedsearch_crawler")
```

 I've been puzzling over the search arguments but really don't know what to make of them :)

`search(url: Union[URL, str, List[Union[URL, str]]])`
or `searchurl: Union([str, List[str]])`

getting syntax errors.. any suggestions or corrections would be appreciated.

```
 File "<stdin>", line 1, in <module>
NameError: name 'search' is not defined
>>> print(feeds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'feeds' is not defined
```

**Comment by infominer33** [comment]
ok, so I"m making progress...  trying a few variations found this doesn't throw an error

but neither is it printing the log output... well, it printed at least once with a helpful error.. but can't get that to happen again.

```
from feedsearch_crawler import searchUnion([str, List[str]])
import logging
logging.basicConfig(filename='example.log',level=logging.DEBUG)
feeds = search('https://aaronparecki.com/articles', 'https://altmode.org', 'https://anon-solutions.ca/blog', 'https://anonyome.com')
print(feeds)
logger = logging.getLogger("feedsearch_crawler")
```
